# Generated by Django 3.2.7 on 2021-09-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usysAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(unique=True, verbose_name='codigo estudiante'),
        ),
    ]
